### PR TITLE
Objects get deleted by Selection Node was fixed and Transaction for Single Context

### PR DESCRIPTION
**Pull request by phliberato**
Fixed issue when AS deleted object after user deleted selection node

### CODE REVIEW

**Comment by phliberato** [comment]
Implemented a transaction manager for single context to use in Select Node.

**Comment by phliberato** [comment]
I set IsOwnedByDynamo to false in both GetDynObjects functions to simplify the code

**Comment by icelook2016** [comment]
@phliberato We are sorry for the delayed answer to these changes. We will review the changes at a later time, when priorities will shift towards working on this. Thank you for your interest in contributing to the Dynamo Extension for Advance Steel.

**Comment by icelook2016** [comment]
@phliberato We are sorry for the delayed answer to these changes. We will review the changes at a later time, when priorities will shift towards working on this. Thank you for your interest in contributing to the Dynamo Extension for Advance Steel.

**Pull request closed without merging**
